packages/record/src/record/record.ts
packages/replayer/src/replayer/replay-events.ts

This makes it easier to view replays when they are running locally.

Specify window to match viewport

---

packages/cli/src/local-data/sessions.ts

* ':' is not a valid character for filenames in Windows, causing issues
for replay

Fix session filenames stored in ~/.meticulous

---

packages/record/src/record/record.ts

* Setting the default viewport to null launches puppeteer with the
maximum allowed view size (matches the winwow size)

Recording: set default viewport to null

---

packages/cli/package.json
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/config/config.ts
packages/cli/src/config/config.types.ts
packages/cli/src/index.ts
packages/cli/src/main.ts
yarn.lock

Usage:
1. Create a test case:
```
npx replay --apiToken=<TOKEN> --sessionId=<SESSION_ID> --appUrl=<APP_URL> --screenshot --headless --save
```
2. Run all tests (e.g. in CI):
```
npx run-all-tests --apiToken=<TOKEN> --appUrl=<APP_URL> --headless
```

Add support to run multiple test replays with Meticulous

---

packages/cli/package.json
packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/download-replay/download-replay.command.ts
packages/cli/src/commands/download-session/download-session.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/commands/show-project/show-project.command.ts
packages/cli/src/commands/upload-build/upload-build.command.ts
packages/cli/src/main.ts
packages/cli/src/utils/sentry.utils.ts
yarn.lock

* Add Sentry for error reporting
* Invoke options are captured.
Note: some command handlers also exit by calling `process.exit(1)` which is not instrumented yet.

Add Sentry to report CLI failures

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/replay-debugger/src/replayer/replay.utils.ts
packages/replayer/src/replayer/replay-events.ts
packages/replayer/src/replayer/replay.utils.ts

Makes `appUrl` optional. Replay will use the start URL if `appUrl`
is not provided.

Default to https for app URL

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/replayer/src/replayer/replay-events.ts

* Content Security Policies may prevent replay from loading js snippets

Replay: add option to bypass CSP

---

packages/cli/src/api/test-run.api.ts
packages/cli/src/commands/update-tests/update-tests.command.ts
packages/cli/src/index.ts
packages/cli/src/main.ts

* `update-tests` can be used after running Meticulous tests to update
the meticulous.json file with new reference replays

Add the update-tests command to update test cases

---

packages/replay-debugger/src/replayer/replay-debugger.ui.ts
packages/replayer/src/index.ts
packages/replayer/src/replayer/replay.utils.ts

This PR adds support for handling window resize events.
For simulation we expose a `setViewport` puppeteer function which is invoked as part of "resize" event simulation.

Replay resize events

---

packages/cli/src/commands/create-test/create-test.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/index.ts
packages/cli/src/main.ts

The `create-test` commands combines recording and simulating (the last
recorded session) to make creating new Meticulous tests simpler for
users.

CLI: add the `create-test` command

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/common/src/types/replay-debugger.types.ts
packages/replay-debugger/src/replayer/replayer.ts
packages/replayer/src/replayer/replay-events.ts
packages/replayer/src/replayer/replay.utils.ts

The session metadata `startURL` is now considered the canonical way of getting the first URL of a session so during replay we should use that.
Most session now should have a startURL defined in metadata but keeping the old event-stream startURL logic in place for backward-compatibility, we can drop it in the future.

Use start URL from session metadata

---

packages/replayer/src/replayer/screenshot.utils.ts

We should display a single next action for the user to take and currently the link into the Meticulous dashboard provides this.

Change screenshot log statement to debug level

---

packages/cli/src/commands/create-test/create-test.command.ts

Tests are based on visual difference of the final simulation state so screenshots are a requirement for creating a test at the moment.

drop screenshot argument of create-test command

---

packages/cli/src/commands/replay/replay.command.ts

In most cases users want a final state screenshot during simulation

set screenshot flag to true by default in simulate command

---

packages/cli/src/commands/bootstrap/bootstrap.command.ts
packages/cli/src/index.ts
packages/cli/src/main.ts
packages/cli/src/utils/npm-set-script.utils.ts

The `bootstrap` commands sets up a npm/yarn project:
* Creates a `meticulous.json` file if one doesn't exist
* Adds a `test:meticulous` script

CLI: add the `bootstrap` command to set up a project

---

packages/cli/src/api/client.ts
packages/cli/src/api/test-run.api.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/utils/run-all-tests.utils.ts

* the `--useCache` option will not re-run passing tests for the same commit

Run all tests: add `--useCache` option

---

packages/cli/src/local-data/replay-assets.ts

Assets locations change per environment and we want to re-fetch any
assets which differ in case of an environment change. Keying the
asset metadata by the output file name ensures a correct etag
comparison (comparing etag of the local file vs the remote origin)
in case of an environment change.

key assets metadata by file name rather than fetch URL location

---

packages/recorder-loader/src/loader.ts

Addressing the comment here: https://github.com/alwaysmeticulous/meticulous-sdk/pull/112#discussion_r992261384
Looks like the isn't much useful contextual information from the script `error` event so I've kept the `script.onerror` `reject()` as is.

bubble up error when rejecting promise in recorder loader

---

packages/cli/src/commands/serve/serve.command.ts
packages/cli/src/main.ts

Add command to spin up a localhost server to serve the assets that were snapshotted when running a particular replay.
I added this mainly for my own usage in debugging, but I think it's useful and worth merging. What do you think?
Downside would be more commands get listed when you run `npx meticulous`, which could make it more confusing for users to learn how to use the product. (ideal thing would be to start grouping the commands into core and advanced, not sure that's possible)

Add serve command

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/image/diff.utils.ts
packages/cli/src/local-data/replays.ts
packages/cli/src/local-data/screenshot-diffs.ts

We're adding the ability to take multiple screenshots during simulations.
This PR extends the existing diffing utilities to handle comparing  simulations with multiple screenshots.
In cases where we have multiple screenshots diffing can "fail" if any of the following is true:
* for any screenshot pair, the pixel mismatch is above the set threshold
* overall pixel mismatch across all screenshot pairs is above the set threshold
* the head simulation is missing a screenshot which is present in the base simulation-- currently we assume the base simulation screenshots are a subset of the the head simulation.
The failing criteria can change in the future but this preserves the current behaviour (as `final-state` screenshots is a special case of the multiple screenshot simulations)

add support for diffing multiple simulation screenshots

---

packages/cli/package.json
packages/cli/src/command-utils/command-utils.ts
packages/cli/src/command-utils/common-options.ts
packages/cli/src/command-utils/common-types.ts
packages/cli/src/commands/create-test/create-test.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/config/config.ts
packages/cli/src/config/config.types.ts
packages/cli/src/deflake-tests/deflake-tests.handler.ts
packages/cli/src/image/diff.utils.ts
packages/cli/src/parallel-tests/messages.types.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/task.handler.ts
packages/cli/src/utils/config.utils.ts
packages/common/src/index.ts
packages/common/src/types/replay.types.ts
packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts
packages/replayer/src/screenshot.utils.ts
yarn.lock

Cleans up our replay options interfaces (now that I added some extra options here it was getting a bit verbose).
For example ReplayExecutionOptions and ScreenshottingOptions. This hopefully makes the code easier to follow, because it reduces the number of options and so makes it easier for readers to see which options are different vs which options are the same between the different interfaces. It should hopefully make it less verbose to pass things around (e.g. often the ReplayExecutionOptions were just getting passed from one method to the next without getting changed).
We try to centralize all defaults at the command level, since then yargs prints out the default value to the user on the help screen, which can be useful for the user. This also means that we can keep the descriptions, …

Deduplicate replay interfaces

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/deflake-tests/deflake-tests.handler.ts

Follow-up to https://github.com/alwaysmeticulous/meticulous-sdk/pull/131/files, we still have two versions of `StoryboardOptions` floating about:
1) https://github.com/alwaysmeticulous/meticulous-sdk/blob/a7333c8e681abd136ca4e1526a24a4f2ae54451a/packages/common/src/types/replay.types.ts#L79
2) https://github.com/alwaysmeticulous/meticulous-sdk/blob/a7333c8e681abd136ca4e1526a24a4f2ae54451a/packages/sdk-bundles-api/src/replay/sdk-to-bundle/index.ts#L30
Will fix that in follow-up PR.

fix dist imports

---

packages/replayer/src/output.utils.ts

This should make uploading/downloading the zips about 25% faster on average.

Don't save copy of rrweb data in replay zip

---

packages/replayer/src/replayer.ts

Very useful for debugging.
Putting this as a env var, rather than a param, since it's really designed for our internal use.

Add ability to hold browser open

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/create-test/create-test.command.ts
packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/common/src/constants.ts
packages/common/src/types/replay-debugger.types.ts
packages/common/src/types/replay.types.ts
packages/replay-debugger/src/replayer/replayer.ts
packages/replayer/src/replayer.ts

This change also changes the replay-debugger command to use `COMMON_REPLAY_OPTIONS`.

Introduce disable remote fonts as option

---

packages/replay-debugger/src/replayer/replayer.ts
packages/replayer/src/index.ts
packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts

Pass original session start URL through to network event stubbing so that it can swap out the origin correctly with the origin that matches the original recorded requests. Currently the origin swapping is broken, because it swaps out the `--appUrl` origin for the `--appUrl` origin.

Pass original session start URL through to network event stubbing

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/common/src/types/replay-debugger.types.ts
packages/replay-debugger/package.json
packages/replay-debugger/src/replayer/debugger.utils.ts
packages/replay-debugger/src/replayer/replayer.ts

This PR updates the `replay-debugger` to use replay v2 snippets, following similar logic to the standard replayer. The control plane in the debugger was already within the node process, so not much of a change in terms of user interaction. The browser context seeding and network stubbing logic is moved to the node process.
Fixes SIM-322

Use replay v2 snippets in simulation debugger

---

packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts

This has always been a CLI option, but previously wasn't wired through.
This is useful for websites which disable unsafe-eval (since we rely on that for Puppeteer injecting code). Ideally we'd still fail any requests that look like they could have side-effects (e.g. XHR, Fetch, navigations with post data/forms etc.) to external URLs for safety, in a way that's robust even if polly errors during initialisation or something. Or at least only allow external URLs to be hit if method is GET and we don't send any cookies with it.

Wire through csp bypassing for replay

---

packages/replayer/src/replay.utils.ts

Currently we do this on the replay-next-node side, but that initializes the console logging too late -- after scripts may have already been evaluated, so it's possible we may miss some errors getting logged out. I'll open a seperate PR to remove it from there.

Log any console messages -> debug as soon as page is created

---

packages/cli/src/commands/run-all-tests/run-all-tests.command.ts

Some initial evidence suggesting that disabling moveBeforeClick _may_ reduce hover flakes, so want to try running our tests a bit more with it disabled to confirm/disconfirm.

Wire through move before click for run-all-tests

---

packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts

If virtual time is enabled then we need to install the virtual event loop before any application code runs, since that code may snapshot copies of the setTimeout etc. functions

Install virtual event loop before rest of page loads

---

packages/recorder-loader/package.json
packages/replay-debugger/package.json
packages/replayer/package.json

The `sdk-bundles-api` package only contains types and so should not be transitively depended on.

Move sdk-bundles-api to devDependencies

---

packages/cli/package.json
packages/cli/src/api/replay-diff.api.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/deflake-tests/deflake-tests.handler.ts
packages/cli/src/local-data/replays.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/common/src/types/replay.types.ts

Update relevant CLI commands to send screenshot diff data to the Meticulous API.
* Diffing screenshots now computes the outcome for all screenshots, so that we can persist the diff data
* When `run-all-tests` is run, the `testRunId` is passed around to be tracked when the screenshot diff data is pushed to the Meticulous API
[SIM-334](https://toil.kitemaker.co/qpgVHi-Meticulous/pPGwrM-Engineering/items/334)

Update the simulate command to send diff data to Meticulous

---

.github/workflows/build.yaml
packages/replay-debugger/src/replayer/debugger.utils.ts
packages/replayer/src/index.ts
packages/replayer/src/replay.utils.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay/sdk-to-bundle/index.ts

This will ensure the values returned by `Date.now()` etc. are always _exactly_ the same on every skip pauses run -- while currently there's non-determinism due the time elapsed from evaluating `patchDate` and evaluating `installVirtualEventLoop` (the later which calls Date.now() on the patched date to work out the start time).
Once this has merged I'll update installVirtualEventLoop to use the passed in timestamp, and to extend from `window.__meticulous.timeshift.OriginalDate` if it exists _and_ if the new sessionStartTime param is being passed through, rather than from `window.Date` (which would shift twice). Since I can do this as a single change there won't be any issues with API breaks (old CLI, new bundle etc.).

Pass through session start time to virtual event loop

---

packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts

We automatically abandon recording rrweb data if it's too large since it's generally not essential for replay. However there is one remaining place where it is essential for replay and that's for when we do date shifting. This PR removes that dependency by falling back to using the user events to calculate the session start and session duration.
This will fix the issue for now, and in the meantime we can work on adding a dedicated session start timestamp (that event.timeStamps are relative to) that's measured in Date.now() time rather than performance.timeOrigin time, to ensure we can reproduce the original Date.now() calls exactly.

Update date shifting to not rely on rrweb

---

packages/cli/src/api/test-run.api.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/config/config.ts
packages/cli/src/config/config.types.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/utils/config.utils.ts
packages/cli/src/utils/run-all-tests.utils.ts

This should enable a workflow where the baseReplayIds are not checked into your meticulous.json file. So if the diffs are intended you can just merge the PR, without having to update your meticulous.json file. The intent is that this will be used as the recommended method for both active and passive tests. The --baseCommitSha will be automatically passed in by a github action that wraps the Meticulous CLI.

Add baseCommitSha argument

---

packages/cli/src/local-data/replay-assets.ts

This makes sure the bundle files are interpreted as CommonJS and not ESM.
See error:
```
Error [ERR_REQUIRE_ESM***: require() of ES Module /app/assets/node-network-stubbing.bundle.js from /app/node_modules/@alwaysmeticulous/replayer/dist/replayer.js not supported.
node-network-stubbing.bundle.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename node-network-stubbing.bundle.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /app/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

Save bundle files with the .cjs extension

---

packages/cli/src/api/test-run.api.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/replay/utils/compute-and-save-diff.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/config/config.types.ts
packages/cli/src/deflake-tests/deflake-tests.handler.ts
packages/cli/src/parallel-tests/messages.types.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/run-all-tests.ts
packages/cli/src/utils/run-all-tests.utils.ts

This is required for https://github.com/alwaysmeticulous/report-diffs-action/pull/26, which is important to ensure we don't report that a session failed with a link when the link leads the user to an empty set of screenshot diffs (e.g. because all sessions completely failed to even run), and since the # differing screens is more useful feedback than the # of differing sessions (the sessions are pretty random, some cover many distinct parts of the app) and lets the user know what to expect when they click the link.

Return screenshot diff results from run-all-tests

---

.github/workflows/build.yaml
lerna.json
package.json
packages/api/src/replay/replay-diff.types.ts
packages/cli/package.json
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/replay/utils/compute-diff.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/config/config.types.ts
packages/cli/src/deflake-tests/deflake-tests.handler.ts
packages/cli/src/parallel-tests/__tests__/merge-test-results.spec.ts
packages/cli/src/parallel-tests/merge-test-results.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/run-all-tests.ts
packages/cli/src/parallel-tests/run-all-tests.types.ts
yarn.lock

Adds the new argument:
**name**: maxRetiresOnFailure
**description**: If set to a value greater than 0 then will re-run any replays that give a screenshot diff and mark them as a flake if the screenshot generated on one of the retryed replays differs from that in the first replay.
And stores such flakes in the backend as:
```ts
export interface ScreenshotDiffResultFlake {
outcome: "flake";
/**
* The original diff. Can be any outcome but for 'no-diff'.
*/
diffToBaseScreenshot: Omit<ScreenshotDiffResult, "identifier">;
/**
* The diffs created by retrying taking the head screenshot and comparing
* it to the original head screenshot. At least one of these will have an
* outcome other than no-diff, hence why this failure is marked as a flake.
*
* Note that in the context of these diffs base …
```

Retry on failure

---

packages/cli/package.json
packages/cli/src/api/replay.api.ts
packages/cli/src/api/session.api.ts
packages/cli/src/local-data/local-data.utils.ts
packages/cli/src/local-data/replays.ts
packages/cli/src/local-data/sessions.ts
yarn.lock

Currently if two processes download the same file at the same time it can cause issues. For example when running with retries I'll often see process A download the zip of a replay, then process B start downloading it, but by the time process B finishes downloading it and starts extracting it, process A has already extracted the zip and deleted it.
By using lock files we also avoid two processes making the same download at the same time. Instead the 2nd will just wait for the first to finish, and then use the already downloaded file.
This uses proper-lockfile under the hood which handles things like left over lockfiles when the application crashes (it bumps mtime every 5s while lockfile is still being used, and ignores lockfiles which haven't been updated for > 10s).

Add locking for downloads & zip extraction

---

packages/api/src/index.ts
packages/api/src/replay/replay-diff.types.ts
packages/cli/src/parallel-tests/__tests__/merge-test-results.spec.ts
packages/cli/src/parallel-tests/merge-test-results.ts

No functional changes. These changes just make the typings far easier to use, and a little more precise. In particular Typescript doesn't like it when you do an `Omit<>` over a discriminated type union -- you lose all type narrowing -- when you filter on an outcome it doesn't filter down the type.

Improve replay diff typings

---

packages/replayer/src/replayer.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay/sdk-to-bundle/index.ts

The user interactions script now depends on pre-navigation page setup.
This PR updates the replayer to call `boostrapUserInteractions` within the `nodeUserInteractions` module, if available.

Bootstrap user interactions

---

packages/common/src/constants.ts

font request interception caching might trigger
a double requestPaused CDP event which triggers "request" Puppeteer event to be emitted twice
which breaks tracking of in-flight requests. See https://bugs.chromium.org/p/chromium/issues/detail?id=1196004 and
https://github.com/puppeteer/puppeteer/issues/7475.

Disable WebFontsCacheAwareTimeoutAdaption

---

packages/api/src/replay/test-run.types.ts

Test runs triggered by workflow dispatch will run on head without comparing to a base commit.

Update workflow dispatch types

---

packages/api/src/index.ts
packages/api/src/organization.types.ts
packages/api/src/project.types.ts
packages/cli/src/api/project.api.ts
packages/cli/src/api/replay.api.ts
packages/cli/src/parallel-tests/run-all-tests.ts
packages/cli/src/utils/run-all-tests.utils.ts

This change pulls the project configuration from the Meticulous API and merge the test cases to run with the ones present in the `meticulous.json` file (if it exists).
[SIM-386](https://toil.kitemaker.co/qpgVHi-Meticulous/pPGwrM-Engineering/items/386)

Add support for session selection from the Meticulous API

---

packages/cli/src/commands/replay/replay.command.ts

Adding more debug logging to help debug some freezes we've seen in some select cases (these freezes appear to occur before simulation starts, but after getReplayCommandId returns, which is odd -- so the extra debug lines will help).

Add more debug logging

---

packages/replayer/src/replayer.ts

This terminates the replay early if timeout occurs while replaying user interaction events

handle simulation timeout errors

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/create-test/create-test.command.ts

This is now the best tested and most reliable way to run the tests (e.g. notice that `--skipPauses false` tests flake a lot on Meticulous CI, but `--skipPauses true` tests do not), so we should default it to true so users get the best experience by default. I'll leave in `--skipPauses false` as a debugging option.

Default --skipPauses to true

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/index.ts
packages/cli/src/main.ts
packages/cli/src/utils/sentry.utils.ts

The GitHub action calls the replay handler directly, skipping the init logic within the CLI.
This PR exposes the Sentry initialisation logic to enable recording GitHub action runs performance data.
Additionally this makes the sample rate configurable and handles cases where replay handler is called within a Sentry transaction (so action runs can be grouped in a single transaction)

Expose Sentry initialization and make sample rate configurable

---

packages/cli/src/commands/replay/replay.command.ts

Don't save session data in replayEventsParams.json (it's already saved in session-data.json, and it's quite big -- ~1.4mb for the sessions I was testing on).

Don't save session data in replayEventsParams.json

---

packages/cli/src/parallel-tests/execute-test-in-child-process.ts
packages/cli/src/parallel-tests/task.handler.ts
packages/cli/src/utils/sentry.utils.ts

This fixes Sentry when running simulations within a child process,
such as when running via `run-all-tests` or the Github Action.

Fix run-all-tests sentry

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/replay/utils/exit-early-if-skip-upload-env-var-set.ts

For many sessions uploading the archive takes up to 9 times as long as the replay itself, so being able to skip the upload stage can speed up testing (e.g. when running command repeatedly in a bash for loop to check for flakey issues).

Allow skipping upload stage when replaying

---

packages/api/package.json
packages/api/tsconfig.json
packages/cli/package.json
packages/cli/tsconfig.json
packages/common/package.json
packages/common/tsconfig.json
packages/record/package.json
packages/record/tsconfig.json
packages/recorder-loader/package.json
packages/recorder-loader/tsconfig.json
packages/replay-debugger-ui/tsconfig.scripts.json
packages/replayer/package.json
packages/replayer/tsconfig.json
packages/sdk-bundles-api/package.json
packages/sdk-bundles-api/tsconfig.json

The `tsconfig.tsbuildinfo` file is a `tsc` build cache and should not be packaged in `./dist`.

Cleanup package.json and tsconfig.json

---

packages/cli/src/api/test-run.api.ts
packages/cli/src/api/types.ts
packages/cli/src/index.ts
packages/cli/src/parallel-tests/run-all-tests.ts

Exposing project data is needed for making the callback hooks logic within the
GitHub Action dependent on the properties of the project of the test run (e.g. 
whether the project has GitHub App integration enabled).

improve test run typings and expose project within run-all-tests callbacks

---

packages/cli/src/config/config.ts
packages/cli/src/utils/config.utils.ts

This PR fixes the CLI support for specifying `appUrl` per test case via the `replay option`. Type-wise it was already supported though we didn't consume the `appUrl` correctly, this fixes it and also updates the replay target generation to take into account the replay option `appUrl` if set. 
Have made `--appUrl` and the per-test-case `appUrl` mutually-exclusive as it can lead to priority confusion but do shout it you think there are cases where we should allow doing this!

Per test-case appUrl support

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts
packages/replayer/package.json
packages/replayer/src/next/utils.ts
packages/replayer/src/replay.utils.ts
packages/replayer/src/replayer.ts
yarn.lock

This PR adds special handling for simulation of sessions with SSRed Next JS pages. We want to avoid hitting SSR pages and instead use Next's router logic of . To achieve this we start simulation from a known non-SSR page, currently `_error` which always 404s and then navigate to the correct start URL via `window.next.router.replace()`. The network stubbing snippet now handles successful mocking of the initial `_next/data` request/

Special handing for NextJS start URLs during simulation

---

packages/replayer/src/replay.utils.ts

The expectation going forward is for the URL observer bundle to be present on all pages as other bundles depend on functions it exposes.
Newer versions of the URL observer bundle won't start the observer by default, in order to enable conditional listening.

explicitly call URL observer start listening function

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/timeline.types.ts

Having `unknown` as a type complicates the consumption of this field within the monorepo.

don't export unknown as timeline entry type

---

packages/api/src/replay/test-run.types.ts
packages/cli/src/commands/bootstrap/bootstrap.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/parallel-tests/messages.types.ts
packages/cli/src/parallel-tests/parallel-replay.handler.ts
packages/cli/src/parallel-tests/parallel-replay.types.ts
packages/cli/src/parallel-tests/run-all-tests.ts
packages/cli/src/parallel-tests/task.handler.ts

This is now handled via `maxRetriesOnFailure`.

drop deflake logic from parallel tests

---

packages/api/src/replay/replay-diff.types.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/parallel-tests/__tests__/merge-test-results.spec.ts
packages/cli/src/parallel-tests/__tests__/parrallel-tests.handler.spec.ts
packages/cli/src/parallel-tests/merge-test-results.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/run-all-tests.ts

This PR adds an optional argument to `runAllTests`. As name suggests it runs tests up to N times, regardless of whether it has a difference to base on the head run.
This is useful for determining flake rate of a given session.

Add flag to re-run tests multiple times

---

packages/api/src/replay/test-run.types.ts
packages/replay-orchestrator/src/test-run/parallel-tests/run-all-tests.ts

This PR updates the `runAllTests` logic to expand the list of test cases to include those from the base test run. This is necessary to prevent a drop in coverage when the project config test cases are updated. Such updates have the potential to entirely replace the set of sessions to run and will occur more frequently in the future.

Expand list of test cases to run with those from the base test run

---

packages/api/src/project.types.ts
packages/cli/package.json
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/replay/utils/replay-debugger.ui.ts
packages/replay-debugger-ui/scripts/index.ts
packages/replay-orchestrator/src/api/replay.api.ts
packages/replay-orchestrator/src/replay/replay-and-store-results.ts
packages/replay-orchestrator/src/test-run/parallel-tests/execute-test-run.ts
packages/replay-orchestrator/src/test-run/parallel-tests/task.handler.ts
packages/replayer/package.json
packages/replayer/src/replayer.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

This should allow us to pull the replay code into the main repo while leaving the replay debugger in the CLI.

Decouple replay debugger from rest of replay code

---

packages/replay-orchestrator/src/replay/replay-and-store-results.ts
packages/sdk-bundles-api/src/replay-orchestrator/README.md
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-test-run.ts

Type as a const of the latest known version, rather than a number, to ensure that all clients bump the version number passed when they upgrade to the types.

maxSemanticVersion typings

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/utils/sentry.utils.ts

NodeJS processes only exit when there are no scheduled setTimeouts/setIntervals etc. left. However I suspect that we have some un-cancelled setTimeouts when our code completes (e.g. maybe Sentry internally, or our replay code somewhere). Depending on zero setTimeouts being pending when the command completes is very fragile (any library can set some setTimeout for any reason), so better to explicitly process.exit(0).

Fix bug where CLI would hang, waiting for a setTimeout, before exiting

---

packages/replay-debugger-ui/scripts/index.ts

We don't depend on the debugger UI port being static so can run it on a random port. This also enables running multiple debuggers locally.

Run debugger UI server on random port

---

packages/common/package.json
packages/common/src/constants.ts

Goal is to unify all call sites which share the same options

define default execution / screenshotting options

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/screenshot-diff-result.ts
packages/replay-orchestrator-launcher/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-scheduled-test-run.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-test-run.ts

Differences in environment, e.g. Puppeteer version change can cause visual diffs not caused by a code change.
This PR introduces an env. version which will be used to compute the overall `screenshotting version` within the bundle.

Introduce and pass environment version for screenshotting bundle

---

packages/cli/src/commands/download-replay/download-replay.command.ts

When debugging replays logs.json can be pretty verbose, so we often use jq to create a more readable version. This is time consuming so this PR updates the CLI to generate it automatically. We could generate it at replay time, but that'd increase the size of the replay zips. So better to generate at consumption time.
Potentially we may want Meticulous BE to generate this instead, and display it in the web-app. However it's not obvious how often the internal logs will be useful for users. I expect we'll want to do this at some point though with the raw console logs. If when we do that we may potentially be able to remove this code here, and add it to the Meticulous FE/BE instead.

Auto-generate logs.concise.txt

---

packages/api/src/project.types.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/utils/apply-default-execution-options-from-project.ts

Testing performed:
- All three mocking modes work when run via CLI
*Do not merge before the corresponding PR on the BE has shipped (this depends on being able to load the project settings, which previously were not returned by the BE controller)*

Use network mocking mode from project settings

---

packages/cli/src/command-utils/common-options.ts
packages/common/src/constants.ts

We'll need to bump the logic version when we bump any dependency on meticulous-sdk.

Turn on move before click by default

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/test-run-environment.ts

For use in push events and triggering test runs on base commits when no previous test run exists.

[gitlab] push event test run context

---

package.json
packages/api/src/index.ts
packages/api/src/sdk-bundle-api/bundle-to-sdk/console-message.ts
packages/cli/package.json
packages/cli/src/commands/download-replay/download-replay.command.ts

See corresponding main Meticulous PR for details.
An example of the concise logs (used for debugging only):
```
[trace-id: 6] [virtual: 1743.60009765625ms, real: 527.5ms] Executing event {"type":"setTimeout","executeAt":1743.60009765625,"id":4,"debugMetadata":{"originalDelay":382}}
[trace-id: 7] [virtual: 1743.60009765625ms, real: 527.7ms] Begun waitUntilDOMStopsChanging
[trace-id: 8] [virtual: 1743.60009765625ms, real: 527.8ms] Triggering 1 virtual animation frame
[trace-id: 5] [virtual: 1743.60009765625ms, real: 528ms] Waited 1 virtual frames for DOM to stop changing
[trace-id: 9] [virtual: 1743.60009765625ms, real: 528ms] Finished executing events up to 1968.60009765625ms. Setting virtual time to 1968.60009765625ms
[trace-id: 12] [virtual: 1968.60009765625ms, real: 533.6ms] Replaying …
```

Handle new logs format

---

packages/client/src/api/replay.api.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-replay.ts
packages/sentry/src/index.ts

The BE now no longer returns the project when getting a replay.

Fix replay types

---

packages/api/src/index.ts
packages/api/src/project.types.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/screenshotting-options.ts
packages/cli/src/commands/replay/replay.command.ts
packages/downloading-helpers/src/scripts/replay-assets.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

This PR adds a couple extra screenshotting options -- optional wait before taking a screenshot and a flag to take a full page screenshot rather than viewport one.
Additionally, these will have default values on project level so `Project` API type is extended to include those.

More screenshotting options

---

packages/downloading-helpers/src/scripts/replays.ts

process.exit bypasses any try/catches if using this as a utility methods (was originally OK-ish since was only used by CLI originally)

Throw instead of process.exit(1)

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

This field isn't set within the session data for newly recorded sessions.

Deprecate requestsBeforeNetworkRecordingStarted

---

packages/cli/package.json
packages/record/package.json
packages/record/src/record/record.ts
packages/replay-orchestrator-launcher/package.json
yarn.lock

As far as I can tell Puppeteer 20 or greater works with Chrome for Testing and Chromium, though I haven't tested the other way around. So let's wait for the main repo PR to merge before merging this PR, and bumping the main repo's SDK dep and reports-diff-action's SDK dep.

Bump to Puppeteer 21

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/screenshot-diff-result.ts

Without the head replay id it's impossible to find / load the correct screenshots for the flake retry

Store head and base replay id for flakes

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Needed for https://github.com/alwaysmeticulous/meticulous/pull/2198
Also removes `VercelExecutionSettings` now that Vercel bypass tokens are handled as part of custom request headers.

Add projectSettingsHash to ReplayExecutionOptions.

---

packages/cli/src/commands/record-login-flow/record-login-flow.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/utils/constants.ts
packages/common/src/index.ts
packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts
packages/record/src/types.ts

Simplifies the injection of recorder scripts by injecting 'v1/meticulous-manual-init.js' and only initializing in intended frames, instead of installing the early network recorder, and then later only injecting 'v1/meticulous.js' in intended frames.
Note that `.on('frame_navigated', frame => frame.evaluate(...))` does not guarantee that the injected code is executed before any other code on the page (and in practice often evaluates it after), which is why the early network recorder used to be required. In contrast evaluateOnNewDocument does provide this guarantee.
This simplification also works around a potential bug in Chrome for Testing, where the combination of the 'v1/meticulous.js' AND the early network recorder javascript AND Chrome for Testing (instead of the older versions of …

Simplify recorder script injection

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/screenshot-diff-result.ts
packages/client/src/api/replay.api.ts
packages/downloading-helpers/src/scripts/replays.ts

This will marginally improve my debugging experience by allowing me to download diff screenshots using the CLI. It also means we handle a return value containing the diffs, which will allow us to start actually returning this from the backend.

Download diffs too when downloading a replay

---

packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.utils.ts

Previously would always give a 'Invalid arguments: should be exactly one string' on Meticulous initialization. I think you get this if you call a Puppeteer exploreFunction while it's still initialising, and the evaluateOnNewDocument must have been happening while `__meticulous_onBeginRecording` was being attached or something. This shifts the ordering to ensure the methods are guaranteed to be bound before they are called.

Fix record login flow 

---

packages/cli/package.json
packages/record/package.json
packages/replay-orchestrator-launcher/package.json
yarn.lock

Looks like 21.9.0 fixes the "aw snap" issues we're seeing when recording.
This also bumps the simulations Chrome version, I'm planning on bumping cloud replay Chrome version / the GH action version after this is merged.
See https://github.com/puppeteer/puppeteer/issues/11672

Bump puppeteer version

---

packages/record/src/record/record-login-flow.ts

We're interested in capturing the application storage right after navigating to the page so there isn't a need to wait for network idle.
Should fix ENG-816

wait for DOMContentLoaded rather than network idle

---

packages/cli/package.json
packages/cli/src/utils/sentry.utils.ts

Previously this would print:
```
Request failed with status code 400
```
Which isn't very informative.
Now it prints:
```
Request failed with status code 400
Session 2024-01-31T18%3A06%<redacted> does not exist
```

Better handling for Axios errors

---

packages/common/src/local-data/local-data.ts

The local data dir defaults to ~/.meticulous and this is normally what is desired and relied upon. We only explicitly set the data dir if:
1. The user passes the --dataDir flag via the CLI
2. In execute session task handler and replay task handler (and in these cases it just grabs `getMeticulousLocalDataDir()` in the spawner process and sends that string through to the spawned process)

Tone down data dir warnings

---

packages/record/src/record/record.utils.ts

`getAllCookies` wasn't defined on the meticulous object when `initMeticulousRecorder` called it which meant we weren't capturing httpOnly cookies properly.
Not sure if there was a reason for providing cookie access after initialising the recorder but this seemed to work from local testing.

Provide cookie access prior to recorder initialisation

---

packages/record/src/record/constants.ts
packages/record/src/record/record.utils.ts

If the URLs required for the recorder get CSP blocked then it'll redirect to:

Add CSP warning

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/websocket-data.ts

Makes it easier to support structured data for specific event types (e.g. "close"), and lays the groundwork for binary message type support.

Break out WebSocket event types into their own interfaces

---

packages/cli/src/commands/record-login/record-login.command.ts
packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.utils.ts

After a matching internal PR is merged, we'll respect this environment variable in the recorder to avoid redacting passwords if we were invoked by the `record-login` CLI command.

Don't redact passwords when recording a login

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/start-local-tunnel/start-local-tunnel.command.ts
packages/cli/src/utils/constants.ts
packages/common/src/constants.ts
packages/common/src/index.ts
packages/sentry/package.json
packages/sentry/src/index.ts

This will prevent stuff ending up in our prod
Sentry when testing stuff locally.

Mark Meticulous super user usage as development

---

packages/remote-replay-launcher/package.json
packages/remote-replay-launcher/src/__tests__/url.utils.spec.ts
packages/remote-replay-launcher/src/index.ts
packages/remote-replay-launcher/src/url.utils.ts

Fix for when a URL's port matches the default for the protocol, the url.port object is an empty string.
This also happens when a port is not provided in the URL.
See note on:
https://developer.mozilla.org/en-US/docs/Web/API/URL/port
Received the error whilst attempting to run the Github cloud action, with a vanilla url (eg "https://pr.somedomain.com"). The URL parsed to a port of "", where parseInt returned NaN.

Default or missing port throws an error

---

packages/tunnel-client/src/lib/tunnel-cluster.ts

We're seeing some requests to secure tunnel deployments timing out / tunnels disconnecting. It looks sometimes we get into a state where the reverse proxy connections are not properly closed leading to sockets being 'stuck' in `FIN-WAIT-2` / `WAIT_CLOSE` states. At some point all connections of the pool get stuck in a shutting down state leading to the tunnel not being able to process any more requests and disconnecing.
TImeouts are also possible due to the constraint connection pool capacity.
This PR updates the secure tunnel client to forcefully shutdown remote connections on error / after connection to the locally exposed service is closed. This shoukd prevent the pool from saturating and properly close the connections.

Force close remote secure tunnel connections

---

packages/downloading-helpers/src/scripts/replay-assets.ts

This is a FLUP from a deadlock in a test case where we had blocked the main thread which had the assets server on it, and so the asset never downloaded. Having a timeout would have made it easier to debug.

Fix freeze if server to download assets from does not respond

---

packages/tunnel-client/src/lib/header-host-transformer.ts
packages/tunnel-client/src/lib/tunnel-connection-cluster.ts
packages/tunnel-client/src/lib/tunnel-multiplexing-cluster.ts

A request to a service running on localhost:8080 would've previously resulted in a request with `Host: localhost` being made. The "default" behaviour is to include the non-standard port as well.

Set port in host header transformer

---

packages/remote-replay-launcher/src/index.ts

If the test run transitions to ExecutionError then instead of exiting immediately we log and message and wait up to 5 minutes for the retry. If it gets retried then we wait for the retry to complete. Note that we will wait a 'wasted' 5 minutes if the test run fails twice in a row, since we only retry once, but we always wait to find a retry -- but that should hopefully be rare / don't think is a huge issue.

Handle tunnel test run retries

---

packages/downloading-helpers/src/scripts/replay-assets.ts

In an upcoming PR, the snippet server will also start serving a WASM file for parsing sourcemaps. This won't come with a sourcemap so the download for a `.map` file below will fail. To avoid a bunch of retries and 1 minute wait, check the extension is `.js` before we try to download a sourcemap.

Don't download source maps for non-JS files

---

.eslintrc.js
packages/cli/src/commands/replay/utils/replay-debugger.ui.ts
packages/cli/src/main.ts
packages/downloading-helpers/src/scripts/replay-assets.ts
packages/record/src/record/record.ts
packages/record/src/record/utils/provide-cookie-access.ts
packages/recorder-loader/src/install-meticulous-intercepts.ts
packages/remote-replay-launcher/src/index.ts
packages/replay-debugger-ui/src/components/replay-debugger/replay-debugger.tsx
packages/replay-debugger-ui/src/components/replay-debugger/user-events.tsx
packages/replay-debugger-ui/src/lib/replay-debugger/replay-debugger.provider.tsx

Existing promises are marked with an `await` where possible/appropriate and `void` otherwise.

Start enforcing no floating promises

---

packages/downloading-helpers/src/scripts/replay-assets.ts

Looks like I broke this some time ago in https://github.com/alwaysmeticulous/meticulous-sdk/pull/551/ so we've been re-downloading the snippets even if we didn't need to.

Fix broken ETag check

---

packages/downloading-helpers/package.json
packages/downloading-helpers/src/file-downloads/download-file.ts
yarn.lock

This is a bit safer in some CI/local scenarios where we might be using the file another thread. It's still not totally safe but that's probably okay since in production we know we never run multiple processes.

Download files atomically

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

GIP set if a page has `getInitialProps`

Add gip field to nextjs-specific application data

---

packages/api/src/index.ts
packages/api/src/project.types.ts

`configurationData` no longer returned by controller endpoints.

Fix project typings

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/test-run-environment.ts
packages/cli/src/commands/replay/replay.command.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

This will enable us to differentiate main branch replays from feature branch replays. Main branch is more useful for tracking changes over time in replay accuracy etc.

Add typings to enable more granular replay analytics

---

packages/tunnel-client/src/lib/tunnel.ts

Previously we used `tunnels.metiuclous.ai` to establish tunnel connections rather than `tunnel-X.tunnels.metiuclous.ai`. This is okay at the moment as both point to the same host but won't be the case in the future.
This change is temporary and assumes that the tunnel URL is a subdomain of the correct host to connect to (e.g `tunnel-1.meticulous.ai` for a tunnel with URL `slug.tunnel-1.meticulous.ai`) which is the case currently. The host and scheme will become BE-driven in future versions

Connect to specific tunnel server when establishing tunnel connections

---

packages/downloading-helpers/src/file-downloads/download-file.ts

Based on the comment for downloadFile, it seems like we need to worry about thread safety for the file where we download the gzip rather than the directory where we unpack the gzip. I hit a bug in https://github.com/alwaysmeticulous/meticulous/pull/3181 because I didn't realize this, so I'm modifying the comment here to make it more clear.

Clarify warning for downloadAndExtractFile

---

packages/replay-debugger-ui/package.json
packages/replay-debugger-ui/src/components/replay-debugger/user-events.tsx
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

The debugger UI deals with event indexes after deduplication (i.e. gets given an event list after deduplication, and sends commands to advance to indexes in the deduplicated list), but we display event numbers to the user as pre-deduplication event numbers, so that they correspond to what they see in the session data.

Improved docs regarding deduped events

---

packages/recorder-loader/README.md
packages/recorder-loader/src/global.d.ts
packages/recorder-loader/src/loader.ts
packages/recorder-loader/src/loader.types.ts

We already block the script from loading so that we don't record replays but this can lead to a 'Meticulous recorder failed to initialise.' error being logged, which often acts as a red herring leading developers down the wrong path when debugging replay issues.

Disable recording replays and change projectId to recordingToken

---

packages/recorder-loader/src/loader.ts

This is safer since some users may not be using ts.

Back compat follow up fix for recordingToken

---

packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/record/middleware.ts
packages/sdk-bundles-api/src/record/record-settings.ts

A new API to allow more comprehensive and flexible redaction of session data than the current redaction API.
We plan to create an open source package to provide higher level utility functions (e.g. `redactJSONResponse<T>(...)`, `redactJWTTokens()`, `redactAuthorizationHeaders()`, `redactJSONPaths(...)`, `asterixOut(...)` etc.) that utilizes the underlying API in this PR. `window.METICULOUS_RECORDER_MIDDLEWARE_V1` will be automatically set by `tryLoadAndStartRecorder` if a middleware option is passed.
Example usage of the _raw_ API (though we expect most users will not use this directly):
```
window.METICULOUS_RECORDER_MIDDLEWARE_V1 = [
{
transformNetworkResponse: (response, metadata) => ({
...response,
content: {
...response.content,
...(response.content.text
? {
text: …
```

Recorder Middleware API

---

packages/sdk-bundles-api/src/record/middleware.ts
packages/sdk-bundles-api/src/record/record-settings.ts

This is important context when performing redaction/transformation (e.g. want to only transform for certain URLs).

Add request to response transformer metadata

---

packages/sdk-bundles-api/src/record/middleware.ts

Just realised allowing network requests to be dropped within transformNetworkResponse would make this behaviour hard to implement:
> Returning null will cause the request and the corresponding response to be dropped from the payload.
At replay time if there is no exact match for a request that is transformed to null **then the request
will be failed with 'net::ERR_FAILED'/'Failed to fetch' rather than automatically trying to find a
'closest match' in the recorded session.**
This is an API break, but this API is not being used yet, so safe to change.

Middleware API fix

---

packages/tunnel-client/package.json
packages/tunnel-client/src/lib/tunnel-http2-cluster.ts
packages/tunnel-client/src/lib/tunnel-multiplexing-cluster.ts
packages/tunnel-client/src/lib/tunnel-multiplexing-pooling-cluster.ts
packages/tunnel-client/src/lib/tunnel.ts
packages/tunnel-client/src/types.ts
yarn.lock

This creates a new secure tunnel server agent which uses HTTP2 under the hood. It is pretty similar to the already existing no-pool multiplexing one but the multiplexing here is done via the native HTTP2 Node implementation rather than an external library.

Tunnel client logic for HTTP2 multiplexing

---

packages/cli/package.json

`3001` works when running the frontend in dev mode (I guess it proxied to 3000 somehow?) but doesn't work when running the frontend in prod mode. `3000` is the correct port and works for both modes.

Fix local API port

---

packages/cli/src/commands/start-local-tunnel/start-local-tunnel.command.ts

Chrome thinks the comma is part of the URL, so, when you click on it, the navigation won't work properly. I think putting user and password on their own line makes them more visible as well.

Don't add comma after tunnel URL

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/replay-divergence.ts

Can be useful context prior to loading the full timeline data.
Used in https://github.com/alwaysmeticulous/meticulous/pull/3892

Add truncated message to DivergenceConsoleError

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts
packages/sdk-bundles-api/src/window-api/public-window-api.ts

This will unblock one of our customers who wants to record files being dropped onto the browser which isn't something our recorder captures at the moment. The biggest open question is whether we allow an async function as a listener and `await` it.

Add API for record/replay of custom events

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/replay-divergence.ts

Changed the console error indicator behavior in https://github.com/alwaysmeticulous/meticulous/pull/3909

Add comment for new console error divergence indicators

---

packages/api/src/index.ts
packages/api/src/replay/test-run-chunk.types.ts
packages/api/src/replay/test-run.types.ts
packages/replay-orchestrator-launcher/src/index.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-scheduled-test-run-chunk.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-test-run.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-scheduled-test-run-chunk.ts

This creates the typings required for test run chunk execution and also exposes `executeTestRunChunk`
in `replay-orchestrator-launcher`.  `executeTestRunChunk` is not part of the bundle yet but there will be no users of it yet.

Create typings for test run chunk execution & expose bundle function for chunked exection

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/screenshot-diff-result.ts

See corresponding main repo PR for details of why we are storing these. I think around 2% of comparisons are diffs, so it shouldn't increase data volume too much (no-diffs take up about 350 bytes; these class names I'd expect on average to take up around 150-300 bytes; so maybe looking at a 1-2% increase in data volume). We could hash the classnames to 4 chars long if we wanted to reduce data usage (collisions aren't catastrophic in our case), but for now not hashing to aid debug-ability).

Store changed sections classnames

---

packages/recorder-loader/package.json
packages/sdk-bundles-api/package.json
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-test-run.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/loglevel.ts

`@alwaysmeticulous/sdk-bundles-api` and its deps are needed at runtime for users of the recorder-loader package.

Move sdk-bundles-api to dependencies

---

packages/recorder-loader/src/get-snippet-version-folder.ts
packages/recorder-loader/src/install-meticulous-intercepts.ts
packages/recorder-loader/src/loader.ts
packages/recorder-loader/src/loader.types.ts

(see e.g. https://snippet.meticulous.ai/record/v/1.0.0/network-recorder.bundle.js)

Allow specifying exact versions

---

packages/tunnel-client/src/localtunnel.ts

This won't work, so let's fail early rather than spending lots of time debugging a hanging connection like I just did.

Fail early if opening a tunnel with the Bun runtime

---

packages/tunnel-client/src/lib/tunnel-http2-cluster.ts

One of our customers has some custom routing logic that gets triggered by `x-forwarded-host`. I think we should make our tunnel more transparent and drop all the headers that aren't part of the original request.

Drop more headers when forwarding requests

---

packages/downloading-helpers/src/index.ts
packages/downloading-helpers/src/scripts/replay-assets.ts

Tested via Node console:
```
> await helpers.checkIfAssetsOutdated(["replay/v2/browser-scripts.bundle.js","replay/v2/snippet-playback.bundle.js"])
{
'replay/v2/browser-scripts.bundle.js': true,
'replay/v2/snippet-playback.bundle.js': true
}
> await helpers.fetchAsset("replay/v2/browser-scripts.bundle.js")
> await helpers.checkIfAssetsOutdated(["replay/v2/browser-scripts.bundle.js","replay/v2/snippet-playback.bundle.js"])
{
'replay/v2/browser-scripts.bundle.js': false,
'replay/v2/snippet-playback.bundle.js': true
}
> await helpers.fetchAsset("replay/v2/snippet-playback.bundle.js")
> await helpers.checkIfAssetsOutdated(["replay/v2/browser-scripts.bundle.js","replay/v2/snippet-playback.bundle.js"])
{
'replay/v2/browser-scripts.bundle.js': false,
'replay/v2/snippet-playback.bundle.js': false …
```

Expose function to check if an asset is outdated

---

packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts

Some CI runners such as CircleCI will timeout the job early if they see no new output.

Output progress for run-all-tests-in-cloud in notty environments

---

packages/downloading-helpers/src/config/snippets.ts
packages/downloading-helpers/src/scripts/replay-assets.ts

Allows running tests comparing multiple versions of snippets simultaneously without them clobbering each other / overwriting each other's cached assets.

Separate asset caches for alternate base URLs

---

packages/client/src/client.ts

Currently a short blip would make the three retries all fail quickly.

Add delay between retries

---

packages/api/src/replay/test-run.types.ts

This PR enables marking test cases as selected. It will be used in the future to optimise session selection just before execution.

Add new field to mark selected test cases

---

packages/api/src/replay/test-run.types.ts

Let's rename the field, to avoid confusion between "Session Selection" and "Relevant Session Execution at PR time". This is a breaking change, but most likely nobody is using this new field yet, so IMO worth to do it now rather than just deprecating the old field.

Rename field to mark relevant test cases

---

packages/api/src/index.ts
packages/api/src/replay/test-run.types.ts

ORM is not compatible with typescript union types, so let's use enum to guarantee better type safety in our data layer
This change and particularly ORM compatibility has been tested via `yarn link`

Use enum for SessionRelevance

---

packages/redaction/src/generic/__tests__/redact-nested-fields.spec.ts
packages/redaction/src/generic/redact-nested-fields/common-redactors.ts
packages/redaction/src/generic/redact-nested-fields/redact-nested-fields.ts

`${string}_name` is too wide a policy since `xyz_name` can often be used for type unions (e.g. `retry_strategy_name` etc.).
This PR makes two changes:
1. Update the typings to allow overriding the default policies
2. Switching from redacting `${string}_name` to just `${string}first_name`, `${string}last_name`, `${string}full_name` etc.
The second change is a breaking change, so will do an appropriate version bump. When clients upgrade if they have any `_name` properties that are not [`${string}first_name`, `${string}last_name`, `${string}full_name`] then they will be forced by compile time checks to now specify an explicit redaction policy for them.

Allow overriding default redaction policies

---

packages/replay-debugger-ui/next-env.d.ts

That job had been failing in the publish workflow since April 2nd b/c a clean build resulted in a modified file and a dirty git state ([commits](https://github.com/alwaysmeticulous/meticulous-sdk/commits/main/)). The diff in this PR is the result of a clean build and should fix the job.

Fix publish-all-packages job

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/network-stubbing.ts

This enables redefining the "identity transformation". It is particularly useful if we want to enable not matching with the canonical identity (and start already with a more advanced redaction)

Support identity override transformations

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/network-stubbing.ts

This is useful if we want to redact somebody if something else matches certain conditions.
For example, redacting the request body if the url matches X

Add where clause in custom transformations

---

packages/remote-replay-launcher/src/upload-assets-and-trigger-test-run.ts

I don't think we have a utility function for this in this repo, so just doing this directly.

Log test run as URL instead of just ID

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

Matches the pattern for other fields we've added to existing session data objects ([e.g.](https://github.com/alwaysmeticulous/meticulous-sdk/blob/main/packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts#L59)), and this typing would have prevented the issue [here](https://github.com/alwaysmeticulous/meticulous/pull/5049). Makes sure we won't hit a similar issue again although most sessions that would have fallen into this category are probably deselected by now.

Update custom events typing to reflect older sessions

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

Also moves the UserId and UserEmail out of being custom data fields and into here so they can fit in with the rest of the new context API.

Create SessionContext type

---

packages/sdk-bundles-api/src/window-api/public-window-api.ts

Only one customer was using these and they have migrated.

Drop deprecated methods

---

packages/cli/src/commands/upload-assets-and-execute-test-run-in-cloud/upload-assets-and-execute-test-run-in-cloud.command.ts
packages/client/src/api/project-deployments.api.ts
packages/remote-replay-launcher/src/types.ts
packages/remote-replay-launcher/src/upload-assets-and-trigger-test-run.ts

This PR enables potentially waiting for base before executing a static assets deployment. If the deployment is not a pull request, we'll not wait (the logics is in the internal end-point)

Wait for base before uploading assets

---

packages/remote-replay-launcher/src/upload-assets-and-trigger-test-run.ts

Static web applications typically have either an index.html file in their root directory. We'll check for both and warn if neither is found.

Warn if no index.html can be found in static assets

---

packages/downloading-helpers/src/scripts/replays.ts

This will be used by the post processing phase to match per-screenshot coverage source maps to paths in code repositories

Also download per-screenshot coverage during post processing

---

packages/tunnel-client/package.json
yarn.lock

v7 is pure ESM, so let's use the last v6 version instead to support customers running without ESM.

Downgrade cacheable-lookup

---

packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts
packages/cli/src/commands/start-local-tunnel/start-local-tunnel.command.ts
packages/tunnel-client/package.json
packages/tunnel-client/src/index.ts
packages/tunnel-client/src/lib/tunnel.ts
packages/tunnel-client/src/lib/worker-entrypoint.ts
packages/tunnel-client/src/tunnel-worker.entrypoint.ts
packages/tunnel-client/src/utils/open-socket.ts

This changes the tunnel client to run multi-threaded. This seems to improve performance, see some results of a local load test below (left=before, right=after). In particular, the rate of errors at this high load is reduced by over an order of magnitude (from 24.2% to 1.5%).

Implement multi-threaded tunnel client

---

packages/cli/src/commands/replay/utils/replay-debugger.ui.ts
packages/replay-debugger-ui/src/components/replay-debugger/replay-debugger.tsx
packages/replay-debugger-ui/src/components/replay-debugger/user-events.tsx

- Fix viewport issue causing content to appear off-screen on initial load by disabling viewport emulation (setting viewport to null instead of 0x0)
- Make question mark icons and section headers non-selectable (select-none)
- Make JSON code blocks fully selectable with select-all for easier copying

Fix replay debugger UI layout and improve text selection

---

packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts
packages/client/src/api/test-run.api.ts
packages/remote-replay-launcher/src/execute-remote-test-run.ts
packages/remote-replay-launcher/src/types.ts

In conjunction with the backend PR in our monorepo, this lets pilot customers selectively enable comments for certain users without having to send us a list that needs to be updated manually.

Wire through --postComment

---

packages/client/src/api/test-run.api.ts

This opens the path towards storing new diversity measures. It has been tested locally on the following internal test run https://app.meticulous.ai/projects/meticulous/meticulous_app_passive_recordings/test-runs/JCBLtNpHMmt9Q6RFTthtDp9dzG

Add types to upload new diversity measures
