alwaysmeticulous/meticulous-sdk

lerna.json
packages/cli/package.json
packages/cli/src/api/replay.api.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/index.ts
packages/cli/src/main.ts
packages/record/package.json
packages/record/src/index.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts
packages/record/tsconfig.json
packages/replayer/package.json
packages/replayer/src/main.ts

* Add command to perform recording of user sessions
* Add package for the recording infra

Add command for manual recording

---

packages/record/src/record/record.utils.ts

Previous method of loading the recording snippet causes iframes to load the snippet too and start pushing payload in parallel to the main window.

Fix multiple recording when iframes are loaded

---

packages/cli/src/commands/record/record.command.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts

* Set the default recording interval to 1 second

Add option to configure the recording upload interval

---

packages/cli/src/api/replay.api.ts
packages/cli/src/api/test-run.api.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/utils/github-summary.utils.ts
packages/record/src/record/record.ts

Fix encoding of links printed to the console

---

packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/main.ts

Use strict option parsing

---

packages/cli/src/commands/record/record.command.ts
packages/common/src/types/record.types.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts

See: https://github.com/alwaysmeticulous/meticulous/pull/463.

Recording: add support for loading and using fetch stalling

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/commands/show-project/show-project.command.ts
packages/cli/src/commands/upload-build/upload-build.command.ts
packages/cli/src/local-data/replay-assets.ts
packages/cli/src/local-data/replays.ts
packages/cli/src/local-data/screenshot-diffs.ts
packages/cli/src/local-data/sessions.ts
packages/cli/src/main.ts
packages/cli/src/utils/commit-sha.utils.ts
packages/cli/src/utils/github-summary.utils.ts
packages/cli/src/utils/logger.utils.ts
packages/common/package.json
packages/common/src/index.ts
packages/common/src/local-data/local-data.ts
packages/common/src/logger/console-logger.ts
packages/common/src/logger/debug-logger.ts
packages/common/src/types/record.types.ts
packages/record/src/record/record.ts
packages/replay-debugger/src/replayer/replayer.ts
packages/replayer/src/replayer/replay-events.ts
packages/replayer/src/replayer/replay.utils.ts
packages/replayer/src/replayer/screenshot.utils.ts
yarn.lock

* Use `loglevel` library and set default log level to 'info'

Update logging to be less verbose by default

---

packages/cli/src/commands/record/record.command.ts
packages/common/src/types/record.types.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts

* Swap `fetch-stall` snippet for `network-recording` after https://github.com/alwaysmeticulous/meticulous/pull/474

Update recording to use early network recording

---

packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/utils/run-all-tests.utils.ts

Sort replay test results according to meticulous.json order

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/parallel-tests/messages.types.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/task.handler.ts
packages/common/src/types/replay-debugger.types.ts
packages/common/src/types/replay.types.ts
packages/replay-debugger/src/replayer/debugger.utils.ts
packages/replay-debugger/src/replayer/replayer.ts
packages/replayer/src/replayer/replay-events.ts
packages/replayer/src/replayer/replay.utils.ts

Time shifting is enabled by default.

Simulation: shift time during simulation by patching Date

---

packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts

Fixes [SIM-95](https://toil.kitemaker.co/qpgVHi-Meticulous/pPGwrM-Engineering/items/95)

Recording: suppress expected errors due to navigation or tab closing

---

packages/cli/src/commands/debug-replay/debug-replay.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/config/snippets.ts
packages/cli/src/errors/config.ts
packages/cli/src/local-data/replay-assets.ts

This will allow changing environment, for example
changing from production to staging / development,
easier.

make base snippets URL configurable via an env variable

---

packages/cli/src/commands/bootstrap/bootstrap.command.ts
packages/replay-debugger/src/replayer/replay-debugger.ui.ts

Also, fix lint warning with the `bootstrap` command handler

Fix the resize event not being correctly handled in the debugger

---

.github/workflows/build.yaml
.github/workflows/publish.yaml

* Also, add yarn and build caching

GitHub actions: update actions to latest version

---

packages/cli/src/commands/create-test/create-test.command.ts
packages/cli/src/commands/replay/replay.command.ts
packages/cli/src/commands/run-all-tests/run-all-tests.command.ts
packages/cli/src/parallel-tests/messages.types.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/task.handler.ts
packages/common/src/types/replay.types.ts
packages/replayer/src/replayer.ts

Add accelerate flag

---

packages/recorder-loader/src/loader.ts

Fixes case where falsy snapshotLinkedStylesheets value isn't set correctly.

Fix snapshotLinkedStylesheets undefined check

---

packages/cli/src/main.ts
packages/cli/src/parallel-tests/task.handler.ts
packages/common/src/index.ts
packages/common/src/local-data/local-data.ts

The intent is to make the use of side-effect explicit to be clear to the reader. I renamed the existing function to get and introduced a new set function which has the side-effect.

Minor refactor of getdatadir

---

packages/cli/src/commands/replay/replay.command.ts
packages/common/src/types/replay.types.ts
packages/replayer/src/replayer.ts

[SIM-307](https://toil.kitemaker.co/qpgVHi-Meticulous/pPGwrM-Engineering/items/307)

Replay: add support for max duration and max events

---

packages/cli/src/index.ts

Expose logger functions to be used by the [GitHub action](https://github.com/alwaysmeticulous/report-diffs-action).

Expose logger functions

---

packages/api/src/replay/test-run.types.ts

Fixes #200, see also related PR: https://github.com/alwaysmeticulous/report-diffs-action/pull/48#discussion_r1040930629

Types: Add support for workflow_dispatch event type in TestRun context

---

packages/cli/src/commands/screenshot-diff/screenshot-diff.command.ts
packages/cli/src/parallel-tests/__tests__/merge-test-results.spec.ts
packages/cli/src/parallel-tests/__tests__/mock-test-results.ts
packages/cli/src/parallel-tests/__tests__/parrallel-tests.handler.spec.ts
packages/cli/src/parallel-tests/execute-replay-in-child-process.ts
packages/cli/src/parallel-tests/execute-test-in-child-process.ts
packages/cli/src/parallel-tests/parallel-tests.handler.ts
packages/cli/src/parallel-tests/run-all-tests.ts

Fixes 3 bugs and adds unit tests (which I probably should have added in the first place). See comments on code for details.

More bug fixes for run all tests algorithm

---

packages/cli/src/utils/run-all-tests.utils.ts

Add back support for repeated test cases

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/record/record.command.ts

...and allow loading local default api token for record command

Set storyboard to true by default

---

packages/replay-orchestrator/src/test-run/parallel-tests/__tests__/merge-test-results.spec.ts
packages/replay-orchestrator/src/test-run/parallel-tests/__tests__/parrallel-tests.handler.spec.ts
packages/replay-orchestrator/src/test-run/parallel-tests/execute-test-in-child-process.ts
packages/replay-orchestrator/src/test-run/parallel-tests/merge-test-results.ts
packages/replay-orchestrator/src/test-run/parallel-tests/parallel-tests.handler.ts
packages/replay-orchestrator/src/test-run/parallel-tests/task.handler.ts

This PR contains a few fixes of bugs encountered while using the "re-run N times flag".
See individual commits for changes.
Commits are logically split so review by commit should be easier.

Fixes for running with N reruns

---

packages/cli/src/commands/replay/replay.command.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

I accidentally added this duplicate in https://github.com/alwaysmeticulous/meticulous-sdk/pull/387

Remove duplicate flag

---

packages/client/package.json
packages/client/src/client.ts
packages/downloading-helpers/package.json
packages/downloading-helpers/src/file-downloads/download-file.ts
packages/downloading-helpers/src/scripts/replay-assets.ts
yarn.lock

This also sets a default timeout of 60 seconds for any API calls

Retry failed idempotent API / asset requests

---

packages/downloading-helpers/package.json
packages/downloading-helpers/src/scripts/replays.ts
yarn.lock

Extract-zip supports streaming which reduces the memory footprint of extracting replay zips

Replace adm-zip with extract-zip

---

packages/api/src/index.ts

Forgot to export it in the previous PR.

Export GitLab Env Contexts

---

packages/downloading-helpers/src/file-downloads/download-file.ts

Set timeout for S3 file downloads

---

packages/downloading-helpers/src/index.ts
packages/downloading-helpers/src/scripts/replays.ts

This will speed up cloud replay a bit.

Allow downloading only screenshots

---

packages/record/src/record/utils/provide-cookie-access.ts

Before it was trying to capture cookies too early

Fix providing cookie access

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/record-login-flow/record-login-flow.command.ts
packages/cli/src/commands/record/record.command.ts
packages/cli/src/main.ts
packages/common/src/index.ts
packages/common/src/types/record.types.ts
packages/record/package.json
packages/record/src/index.ts
packages/record/src/record/constants.ts
packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.ts
packages/record/src/record/record.utils.ts
packages/record/src/record/utils/expose-new-recording-callback.ts
packages/record/src/record/utils/inject-finish-recording-frame.ts
packages/record/src/record/utils/print-page-close-warning.ts
packages/record/src/record/utils/print-warning.ts
yarn.lock

This creates a command to record login flow sessions.
Review by commit might be easier here, first few commits include some refactoring and dropping of unused args in the recorder.

Create record-login command

---

packages/downloading-helpers/src/scripts/replay-assets.ts

This will facilitate debugging by allowing us to attach a debugger and see the actual sources when debugging changes to the snippets.

Fetch sourcemaps when running against local snippet server

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/record-login/record-login.command.ts
packages/cli/src/commands/record/record.command.ts
packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.ts
packages/record/src/types.ts

[record-login] Wait for session data to save before exiting, and add --appUrl parameters

---

packages/replay-debugger-ui/src/components/replay-debugger/user-events.tsx

Since we'll soon be recording these.

Add a case for mouse move events

---

packages/api/src/replay/replay.types.ts
packages/downloading-helpers/src/scripts/replays.ts

There's no more v1 or v2 replays so we don't need this code anymore.

Remove code for pre-v3 replays

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/bundle-to-sdk/screenshot-diff-result.ts

This should make debugging easier

Add more redaction context to screenshot diff result

---

packages/downloading-helpers/src/scripts/replays.ts

This code is kind of broken at the moment, although until the waiting for base screenshots work this wasn't being surfaced as we weren't hitting the race conditions in it (or at least, if we were this wasn't being surfaced: it might have subtly caused some missing base screenshots).
The problem here is that we use the `metadata.json` file to decide if the replay has been previously downloaded. But when the scope is set to `screenshots-only` we don't actually download this file. So, if two processes simultaenously try to download just screenshots, they'll both perform the download. The locking makes sure that only one is downloading at a given time, but the second one to arrive will start overwriting the files that the first one might now have gone on to read. This can lead to corrupted …

Fix concurrency problems in replay download

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Tiny schema change here is needed before the bigger PR in our monorepo that will actually do useful stuff.

Add `extraCookies` field to `ReplayExecutionOptions`

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/network-stubbing.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Needed for https://github.com/alwaysmeticulous/meticulous/pull/2598

WebSocket data types

---

packages/api/src/index.ts

Used in https://github.com/alwaysmeticulous/meticulous/pull/2618

Export SequenceNumber

---

packages/record/src/index.ts
packages/record/src/record/utils/cookie-helpers.ts
packages/record/src/record/utils/provide-cookie-access.ts

There's a place in the main repo where I want to use this same logic, so let's put it in a utils function and export it for that purpose.

Export cookies conversion method

---

packages/client/src/api/test-run.api.ts

Better error message for in cloud test run creation

---

packages/downloading-helpers/src/scripts/replay-assets.ts

This makes sure a WASM file that we'll be serving soon doesn't get mucked up by a round trip through UTF-8 encoding/decoding.

Download assets as binary

---

packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-replay.ts

Will be used by coverage work.

Add `replayDir` to type

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/bundle-to-sdk/replay-divergence.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-replay.ts
packages/sdk-bundles-api/src/replay-orchestrator/bundle-to-sdk/execute-test-run.ts

Needed for https://github.com/alwaysmeticulous/meticulous/pull/3125

Divergence types

---

packages/api/src/index.ts

forgot to push up a local commit before merging https://github.com/alwaysmeticulous/meticulous-sdk/pull/659

Divergence type FLUP

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

Used by https://github.com/alwaysmeticulous/meticulous/pull/3266

Support Indexed DB

---

packages/cli/src/commands/replay/replay.command.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Used in an upcoming internal PR.

Add disableAssetCache option

---

packages/client/src/api/test-run.api.ts

As suggested by @alexivanov in https://github.com/alwaysmeticulous/report-diffs-action/pull/492#discussion_r1718583566

Add method for emitting telemetry

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/bundle-to-sdk/replay-divergence.ts

Needed for https://github.com/alwaysmeticulous/meticulous/pull/3395

Initial navigation divergence indicator types

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/test-run-environment.ts
packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts
packages/client/src/api/deployment-lock.api.ts
packages/client/src/api/test-run.api.ts
packages/remote-replay-launcher/src/index.ts
packages/remote-replay-launcher/src/types.ts

See also the matching internal PR.

Handle deployment locking

---

packages/api/src/project.types.ts

This will enable higher signal to noise ratio alerts

Add isMonitoringEnabled to project types

---

packages/api/src/sdk-bundle-api/bundle-to-sdk/replay-divergence.ts

Needed for https://github.com/alwaysmeticulous/meticulous/pull/3593

Add type to support pending request divergences

---

packages/cli/package.json
packages/record/package.json
packages/record/src/record/record-login-flow.ts
packages/record/src/record/record.ts
packages/replay-orchestrator-launcher/package.json
yarn.lock

After merging and releasing in this repo I plan to do more testing before bumping the main repo's dependency on this.

Bump Puppeteer version

---

packages/redaction/README.md
packages/redaction/package.json
packages/redaction/src/generic/__tests__/redact-recursively.spec.ts
packages/redaction/src/generic/asterix-out.ts
packages/redaction/src/generic/redact-recursively.ts
packages/redaction/src/index.ts
packages/redaction/src/network-requests/drop-request-header.ts
packages/redaction/src/network-responses/__tests__/transform-json-response.spec.ts
packages/redaction/src/network-responses/transform-json-response.ts
packages/redaction/tsconfig.json
packages/sdk-bundles-api/src/record/middleware.ts
yarn.lock

See `packages/redaction/README.md` for usage examples

Add redaction package

---

packages/sdk-bundles-api/src/record/middleware.ts

Technically an API break but this API isn't used yet.

Update indexed DB middleware API

---

package.json
turbo.json
yarn.lock

Config migration done via `npx @turbo/codemod migrate`

Upgrade to latest Turborepo version

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Will be used in upcoming internal PR.

Add enableCssCoverage to ReplayExecutionOptions

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

See corresponding internal PR for more details.

Add snapshotAssets to replay options

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

See https://github.com/alwaysmeticulous/meticulous/pull/4080

Extend IDB metadata type to support custom size estimates

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

See https://github.com/alwaysmeticulous/meticulous/pull/4088

Support snapshotting IDB entries on read

---

packages/redaction/src/generic/do-not-redact.ts
packages/redaction/src/generic/redact-nested-fields/redact-nested-fields.ts

Faster performance and some small tweaks

Redaction improvements

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

See https://github.com/alwaysmeticulous/meticulous/pull/4201 for context.

Extend custom data to support some internal values

---

packages/client/src/api/github-cloud-replay.api.ts
packages/client/src/api/project.api.ts

See the corresponding internal PR. Now that this supports more than just GitHub, I've moved it so this PR does the renaming.

Rename repo-url endpoint

---

packages/client/src/errors.ts

FLUP to https://github.com/alwaysmeticulous/meticulous-sdk/pull/769

Improved default Axios error messages

---

packages/tunnel-client/src/lib/tunnel-http2-cluster.ts
packages/tunnel-client/src/lib/tunnel.ts

See internal Slack for more details.

Handle original host headers

---

packages/client/src/api/test-run.api.ts
packages/remote-replay-launcher/src/index.ts
packages/remote-replay-launcher/src/types.ts

No interesting logic here, everything meaningful is in the other two repos.

Thread through pullRequestHostingProviderId

---

packages/remote-replay-launcher/package.json
packages/remote-replay-launcher/src/index.ts
packages/remote-replay-launcher/src/resource-tracker.ts
yarn.lock

Should make it more visible to us and users when there is resource contention.

Detect heavy load while tunnel is running

---

packages/cli/package.json
packages/cli/src/utils/sentry.utils.ts
packages/remote-replay-launcher/package.json
packages/sentry/package.json
packages/sentry/src/index.ts
yarn.lock

There's a mismatch with the `report-diffs-action` repo which is causing problems so let's bump both to the latest.

Bump Sentry

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/test-run-environment.ts

FLUP to https://github.com/alwaysmeticulous/meticulous/pull/4565

Update context type comments to align with new prefix

---

packages/cli/src/commands/replay/replay.command.ts
packages/sdk-bundles-api/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Context in https://github.com/alwaysmeticulous/meticulous/pull/4710

Add CLI options to assist in network request debugging

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

See also internal PR that uses this.

Add disableRrweb to ReplayExecutionOptions

---

packages/cli/src/command-utils/common-options.ts
packages/cli/src/commands/record/record.command.ts
packages/record/src/record/record.ts
packages/record/src/types.ts

Useful for debugging payload size issues for both us and customers.

Add record cli option to set max payload size

---

packages/api/src/index.ts
packages/api/src/sdk-bundle-api/sdk-to-bundle/asset-upload-metadata.ts

Currently this can only contain a set of rewrite rules, but making it it's own type so we can expand this in future.

Add typings for asset upload metadata

---

packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Addresses a comment from Alex in internal PR.

Extend ReplayTarget to include S3

---

packages/remote-replay-launcher/src/upload-assets-and-trigger-test-run.ts

This might fix, and if not will help debug, an issue a customer is facing with this.

More logging and tweaks to asset upload

---

packages/cli/src/commands/replay/replay.command.ts
packages/client/src/api/project-deployments.api.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

Migrate to uploaded-assets:// urls (2/5)

---

packages/cli/src/commands/replay/replay.command.ts
packages/client/src/api/project-deployments.api.ts
packages/client/src/index.ts
packages/sdk-bundles-api/src/replay-orchestrator/sdk-to-bundle/execute-replay.ts

After the internal PRs have shipped this code will be dead code.

Migrate to uploaded-assets:// urls (4/5)

---

packages/sdk-bundles-api/src/window-api/public-window-api.ts

The implementation is not even started yet, but opening this up anyway to get some feedback on the typings.

Add typings for context API

---

packages/api/src/sdk-bundle-api/sdk-to-bundle/session-data.ts

Used in https://github.com/alwaysmeticulous/meticulous/pull/5093

New internal key to track failures recording custom objects

---

packages/api/src/replay/test-run.types.ts

Added a new enum value to track whether a session comes from a PR's author

Add `IsPrAuthor` session relevance

---

packages/downloading-helpers/src/scripts/replays.ts

These are in an archive that we want to unzip into its own folder similar to snapshotted assets, so let's share the logic for that.

Handle downloading of per-screenshot coverage data

---

packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts

Also consider skipped sessions when updating the Progress Bar (used by the CLI and in turn by other providers)

Fix Test Run execution progress

---

packages/tunnel-client/src/lib/tunnel.ts

For the customer who needs to use the tunnel behind a proxy.

Support proxy when opening socket

---

packages/cli/src/commands/run-all-tests-in-cloud/run-all-tests-in-cloud.command.ts
packages/cli/src/commands/upload-assets-and-execute-test-run-in-cloud/upload-assets-and-execute-test-run-in-cloud.command.ts
packages/client/src/api/project-deployments.api.ts
packages/client/src/api/test-run.api.ts
packages/remote-replay-launcher/src/asset-upload-utils.ts
packages/remote-replay-launcher/src/execute-remote-test-run.ts
packages/remote-replay-launcher/src/index.ts
packages/remote-replay-launcher/src/types.ts
packages/remote-replay-launcher/src/upload-assets-and-trigger-test-run.ts

This still needs testing once the server-side changes are shipped. It also needs a bit of tidying up, but putting this up for review given the time zone difference so I can have some comments to work on tomorrow.

Implement companion assets
